from PyQt5 import QtCore, QtWidgets, QtGui

class GenerateDialogWindowView(object):
    def setupUi(self, GenerateDialogWindow):
        GenerateDialogWindow.setObjectName("GenerateDialogWindow")
        GenerateDialogWindow.resize(268, 129)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GenerateDialogWindow.sizePolicy().hasHeightForWidth())
        GenerateDialogWindow.setSizePolicy(sizePolicy)
        GenerateDialogWindow.setMinimumSize(QtCore.QSize(200, 100))
        GenerateDialogWindow.setMaximumSize(QtCore.QSize(268, 129))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GenerateDialogWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keyWordLabel = QtWidgets.QLabel(GenerateDialogWindow)
        self.keyWordLabel.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.keyWordLabel.setObjectName("keyWordLabel")
        self.verticalLayout.addWidget(self.keyWordLabel)
        self.keyWordInput = QtWidgets.QLineEdit(GenerateDialogWindow)
        self.keyWordInput.setObjectName("keyWordInput")
        self.verticalLayout.addWidget(self.keyWordInput)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.difficultyLabel = QtWidgets.QLabel(GenerateDialogWindow)
        self.difficultyLabel.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.difficultyLabel.setObjectName("difficultyLabel")
        self.verticalLayout_3.addWidget(self.difficultyLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonEasyDifficulty = QtWidgets.QRadioButton(GenerateDialogWindow)
        self.radioButtonEasyDifficulty.setObjectName("radioButtonEasyDifficulty")
        self.horizontalLayout_3.addWidget(self.radioButtonEasyDifficulty)
        self.radioButtonMediumDifficulty = QtWidgets.QRadioButton(GenerateDialogWindow)
        self.radioButtonMediumDifficulty.setObjectName("radioButtonMediumDifficulty")
        self.radioButtonMediumDifficulty.setChecked(True)
        self.horizontalLayout_3.addWidget(self.radioButtonMediumDifficulty)
        self.radioButtonHardDifficulty = QtWidgets.QRadioButton(GenerateDialogWindow)
        self.radioButtonHardDifficulty.setObjectName("radioButtonHardDifficulty")
        self.horizontalLayout_3.addWidget(self.radioButtonHardDifficulty)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(GenerateDialogWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(GenerateDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(GenerateDialogWindow)

    def retranslateUi(self, GenerateDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        GenerateDialogWindow.setWindowTitle(_translate("GenerateDialogWindow", "Диалоговое окно"))
        self.keyWordLabel.setText(_translate("GenerateDialogWindow", "Ключевое слово:"))
        self.difficultyLabel.setText(_translate("GenerateDialogWindow", "Сложность кроссворда:"))
        self.radioButtonEasyDifficulty.setText(_translate("GenerateDialogWindow", "Легкий"))
        self.radioButtonMediumDifficulty.setText(_translate("GenerateDialogWindow", "Средний"))
        self.radioButtonHardDifficulty.setText(_translate("GenerateDialogWindow", "Сложный"))


class LoadDialogWindowView(object):
    def setupUi(self, LoadDialogWindow):
        LoadDialogWindow.setObjectName("LoadDialogWindow")
        LoadDialogWindow.resize(390, 100)
        LoadDialogWindow.setMaximumSize(QtCore.QSize(4000, 100))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LoadDialogWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pathLabel = QtWidgets.QLabel(LoadDialogWindow)
        self.pathLabel.setObjectName("pathLabel")
        self.verticalLayout.addWidget(self.pathLabel)
        self.loadHorizontalLayout = QtWidgets.QHBoxLayout()
        self.loadHorizontalLayout.setSpacing(0)
        self.loadHorizontalLayout.setObjectName("loadHorizontalLayout")
        self.pathInput = QtWidgets.QLineEdit(LoadDialogWindow)
        self.pathInput.setObjectName("pathInput")
        self.loadHorizontalLayout.addWidget(self.pathInput)
        self.browseButton = QtWidgets.QDialogButtonBox(LoadDialogWindow)
        self.browseButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.browseButton.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.browseButton.setObjectName("browseButton")
        self.loadHorizontalLayout.addWidget(self.browseButton)
        self.verticalLayout.addLayout(self.loadHorizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoadDialogWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(LoadDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadDialogWindow)

    def retranslateUi(self, LoadDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadDialogWindow.setWindowTitle(_translate("LoadDialogWindow", "Диалоговое окно"))
        self.pathLabel.setText(_translate("LoadDialogWindow", "Путь к файлу:"))


class StartScreenView(object):
    def setupUi(self, start_screen):
        start_screen.setObjectName("start_screen")
        start_screen.resize(596, 413)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        start_screen.setPalette(palette)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(start_screen)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_logo = QtWidgets.QLabel(start_screen)
        self.label_logo.setMinimumSize(QtCore.QSize(230, 192))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("UI\\raw\\../Media/crossword generator logo.png"))
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout.addWidget(self.label_logo)
        self.label_title = QtWidgets.QLabel(start_screen)
        self.label_title.setMinimumSize(QtCore.QSize(199, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.horizontalLayout_generate = QtWidgets.QHBoxLayout()
        self.horizontalLayout_generate.setObjectName("horizontalLayout_generate")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_generate.addItem(spacerItem)
        self.generateButton = QtWidgets.QPushButton(start_screen)
        self.generateButton.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout_generate.addWidget(self.generateButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_generate.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_generate)
        self.horizontalLayout_load = QtWidgets.QHBoxLayout()
        self.horizontalLayout_load.setObjectName("horizontalLayout_load")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_load.addItem(spacerItem2)
        self.loadButton = QtWidgets.QPushButton(start_screen)
        self.loadButton.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_load.addWidget(self.loadButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_load.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_load)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(start_screen)
        QtCore.QMetaObject.connectSlotsByName(start_screen)

    def retranslateUi(self, start_screen):
        _translate = QtCore.QCoreApplication.translate
        start_screen.setWindowTitle(_translate("start_screen", "Стартовое окно"))
        self.label_title.setText(_translate("start_screen", "ГЕНЕРАТОР КРОССВОРДА"))
        self.generateButton.setText(_translate("start_screen", "Сгенерировать"))
        self.loadButton.setText(_translate("start_screen", "Загрузить"))
