# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtWidgets, QtGui


class GenerateDialogWindowView(object):
    def setupUi(self, GenerateDialogWindow):
        GenerateDialogWindow.setObjectName("GenerateDialogWindow")
        GenerateDialogWindow.resize(268, 129)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GenerateDialogWindow.sizePolicy().hasHeightForWidth())
        GenerateDialogWindow.setSizePolicy(sizePolicy)
        GenerateDialogWindow.setMinimumSize(QtCore.QSize(200, 100))
        GenerateDialogWindow.setMaximumSize(QtCore.QSize(268, 129))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GenerateDialogWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keyWordLabel = QtWidgets.QLabel(GenerateDialogWindow)
        self.keyWordLabel.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.keyWordLabel.setObjectName("keyWordLabel")
        self.verticalLayout.addWidget(self.keyWordLabel)
        self.keyWordInput = QtWidgets.QLineEdit(GenerateDialogWindow)
        self.keyWordInput.setObjectName("keyWordInput")
        self.verticalLayout.addWidget(self.keyWordInput)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.difficultyLabel = QtWidgets.QLabel(GenerateDialogWindow)
        self.difficultyLabel.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.difficultyLabel.setObjectName("difficultyLabel")
        self.verticalLayout_3.addWidget(self.difficultyLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.difficultyButtonGroup = QtWidgets.QButtonGroup()
        self.radioButtonEasyDifficulty = QtWidgets.QRadioButton(GenerateDialogWindow)
        self.radioButtonEasyDifficulty.setObjectName("radioButtonEasyDifficulty")
        self.horizontalLayout_3.addWidget(self.radioButtonEasyDifficulty)
        self.radioButtonMediumDifficulty = QtWidgets.QRadioButton(GenerateDialogWindow)
        self.radioButtonMediumDifficulty.setObjectName("radioButtonMediumDifficulty")
        self.radioButtonMediumDifficulty.setChecked(True)
        self.horizontalLayout_3.addWidget(self.radioButtonMediumDifficulty)
        self.radioButtonHardDifficulty = QtWidgets.QRadioButton(GenerateDialogWindow)
        self.radioButtonHardDifficulty.setObjectName("radioButtonHardDifficulty")
        self.difficultyButtonGroup.addButton(self.radioButtonEasyDifficulty)
        self.difficultyButtonGroup.addButton(self.radioButtonMediumDifficulty)
        self.difficultyButtonGroup.addButton(self.radioButtonHardDifficulty)
        self.horizontalLayout_3.addWidget(self.radioButtonHardDifficulty)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(GenerateDialogWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(GenerateDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(GenerateDialogWindow)

    def retranslateUi(self, GenerateDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        GenerateDialogWindow.setWindowTitle(_translate("GenerateDialogWindow", "Диалоговое окно"))
        self.keyWordLabel.setText(_translate("GenerateDialogWindow", "Ключевое слово:"))
        self.difficultyLabel.setText(_translate("GenerateDialogWindow", "Сложность кроссворда:"))
        self.radioButtonEasyDifficulty.setText(_translate("GenerateDialogWindow", "Легкий"))
        self.radioButtonMediumDifficulty.setText(_translate("GenerateDialogWindow", "Средний"))
        self.radioButtonHardDifficulty.setText(_translate("GenerateDialogWindow", "Сложный"))


class LoadDialogWindowView(object):
    def setupUi(self, LoadDialogWindow):
        LoadDialogWindow.setObjectName("LoadDialogWindow")
        LoadDialogWindow.resize(390, 100)
        LoadDialogWindow.setMaximumSize(QtCore.QSize(4000, 100))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LoadDialogWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pathLabel = QtWidgets.QLabel(LoadDialogWindow)
        self.pathLabel.setObjectName("pathLabel")
        self.verticalLayout.addWidget(self.pathLabel)
        self.loadHorizontalLayout = QtWidgets.QHBoxLayout()
        self.loadHorizontalLayout.setSpacing(0)
        self.loadHorizontalLayout.setObjectName("loadHorizontalLayout")
        self.pathInput = QtWidgets.QLineEdit(LoadDialogWindow)
        self.pathInput.setObjectName("pathInput")
        self.loadHorizontalLayout.addWidget(self.pathInput)
        self.browseButton = QtWidgets.QDialogButtonBox(LoadDialogWindow)
        self.browseButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.browseButton.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.browseButton.setObjectName("browseButton")
        self.loadHorizontalLayout.addWidget(self.browseButton)
        self.verticalLayout.addLayout(self.loadHorizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoadDialogWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(LoadDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadDialogWindow)

    def retranslateUi(self, LoadDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadDialogWindow.setWindowTitle(_translate("LoadDialogWindow", "Диалоговое окно"))
        self.pathLabel.setText(_translate("LoadDialogWindow", "Путь к файлу:"))


class StartScreenView(object):
    def setupUi(self, start_screen):
        start_screen.setObjectName("start_screen")
        start_screen.resize(596, 413)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        start_screen.setPalette(palette)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(start_screen)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_logo = QtWidgets.QLabel(start_screen)
        self.label_logo.setMinimumSize(QtCore.QSize(230, 192))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("UI\\raw\\../Media/crossword generator logo.png"))
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout.addWidget(self.label_logo)
        self.label_title = QtWidgets.QLabel(start_screen)
        self.label_title.setMinimumSize(QtCore.QSize(199, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.horizontalLayout_generate = QtWidgets.QHBoxLayout()
        self.horizontalLayout_generate.setObjectName("horizontalLayout_generate")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_generate.addItem(spacerItem)
        self.generateButton = QtWidgets.QPushButton(start_screen)
        self.generateButton.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout_generate.addWidget(self.generateButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_generate.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_generate)
        self.horizontalLayout_load = QtWidgets.QHBoxLayout()
        self.horizontalLayout_load.setObjectName("horizontalLayout_load")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_load.addItem(spacerItem2)
        self.loadButton = QtWidgets.QPushButton(start_screen)
        self.loadButton.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_load.addWidget(self.loadButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_load.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_load)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(start_screen)
        QtCore.QMetaObject.connectSlotsByName(start_screen)

    def retranslateUi(self, start_screen):
        _translate = QtCore.QCoreApplication.translate
        start_screen.setWindowTitle(_translate("start_screen", "Стартовое окно"))
        self.label_title.setText(_translate("start_screen", "ГЕНЕРАТОР КРОССВОРДА"))
        self.generateButton.setText(_translate("start_screen", "Сгенерировать"))
        self.loadButton.setText(_translate("start_screen", "Загрузить"))


class MainWindowView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 700)
        MainWindow.setMinimumSize(QtCore.QSize(700, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.descriptions_label = QtWidgets.QLabel(self.centralwidget)
        self.descriptions_label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.descriptions_label.setFont(font)
        self.descriptions_label.setObjectName("descriptions_label")
        self.verticalLayout.addWidget(self.descriptions_label)
        self.descriptions = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptions.sizePolicy().hasHeightForWidth())
        self.descriptions.setSizePolicy(sizePolicy)
        self.descriptions.setMinimumSize(QtCore.QSize(450, 250))
        self.descriptions.setMaximumSize(QtCore.QSize(650, 350))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(201, 201, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 201, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 201, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.descriptions.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setPixelSize(19)
        self.descriptions.setFont(font)
        self.descriptions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.descriptions.setStyleSheet("")
        self.descriptions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.descriptions.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.descriptions)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(197, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.menubar.setPalette(palette)
        self.menubar.setStyleSheet("background-color: rgb(197, 197, 197);")
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setStyleSheet("border-color: rgb(150, 150, 150);")
        self.file_menu.setTearOffEnabled(False)
        self.file_menu.setSeparatorsCollapsible(False)
        self.file_menu.setObjectName("file_menu")
        self.view_menu = QtWidgets.QMenu(self.menubar)
        self.view_menu.setObjectName("view_menu")
        MainWindow.setMenuBar(self.menubar)
        self.save_action = QtWidgets.QAction(MainWindow)
        self.save_action.setObjectName("save_action")
        self.generate_action = QtWidgets.QAction(MainWindow)
        self.generate_action.setObjectName("generate_action")
        self.load_action = QtWidgets.QAction(MainWindow)
        self.load_action.setObjectName("load_action")
        self.hide_words_action = QtWidgets.QAction(MainWindow)
        self.hide_words_action.setObjectName("hide_words_action")
        self.hide_words_action.setCheckable(True)
        self.hide_descriptions_action = QtWidgets.QAction(MainWindow)
        self.hide_descriptions_action.setObjectName("hide_descriptions_action")
        self.hide_descriptions_action.setCheckable(True)
        self.roll_action = QtWidgets.QAction(MainWindow)
        self.roll_action.setObjectName("roll_action")
        self.file_menu.addAction(self.generate_action)
        self.file_menu.addAction(self.load_action)
        self.file_menu.addAction(self.save_action)
        self.view_menu.addAction(self.hide_words_action)
        self.view_menu.addAction(self.hide_descriptions_action)
        self.view_menu.addAction(self.roll_action)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное окно"))
        self.descriptions_label.setText(_translate("MainWindow", "Описания:"))
        self.file_menu.setTitle(_translate("MainWindow", "Файл"))
        self.view_menu.setTitle(_translate("MainWindow", "Вид"))
        self.save_action.setText(_translate("MainWindow", "Сохранить как.."))
        self.generate_action.setText(_translate("MainWindow", "Создать новый"))
        self.load_action.setText(_translate("MainWindow", "Загрузить"))
        self.hide_words_action.setText(_translate("MainWindow", "Скрыть слова"))
        self.hide_descriptions_action.setText(_translate("MainWindow", "Скрыть описания"))
        self.roll_action.setText(_translate("MainWindow", "Перевернуть кроссворд"))
