# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\raw\StartScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiStartScreen(object):
    def setupUi(self, start_screen):
        start_screen.setObjectName("start_screen")
        start_screen.resize(596, 413)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        start_screen.setPalette(palette)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(start_screen)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_logo = QtWidgets.QLabel(start_screen)
        self.label_logo.setMinimumSize(QtCore.QSize(230, 192))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("UI\\raw\\../media/crossword generator logo.png"))
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout.addWidget(self.label_logo)
        self.label_title = QtWidgets.QLabel(start_screen)
        self.label_title.setMinimumSize(QtCore.QSize(199, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.horizontalLayout_generate = QtWidgets.QHBoxLayout()
        self.horizontalLayout_generate.setObjectName("horizontalLayout_generate")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_generate.addItem(spacerItem)
        self.generateButton = QtWidgets.QPushButton(start_screen)
        self.generateButton.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout_generate.addWidget(self.generateButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_generate.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_generate)
        self.horizontalLayout_load = QtWidgets.QHBoxLayout()
        self.horizontalLayout_load.setObjectName("horizontalLayout_load")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_load.addItem(spacerItem2)
        self.loadButton = QtWidgets.QPushButton(start_screen)
        self.loadButton.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_load.addWidget(self.loadButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_load.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_load)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(start_screen)
        QtCore.QMetaObject.connectSlotsByName(start_screen)

    def retranslateUi(self, start_screen):
        _translate = QtCore.QCoreApplication.translate
        start_screen.setWindowTitle(_translate("start_screen", "Стартовое окно"))
        self.label_title.setText(_translate("start_screen", "ГЕНЕРАТОР КРОССВОРДА"))
        self.generateButton.setText(_translate("start_screen", "Сгенерировать"))
        self.loadButton.setText(_translate("start_screen", "Загрузить"))
